
image:
  - Visual Studio 2017
  - Visual Studio 2019

configuration:
  - Release

install:
  - cinst --allow-empty-checksums smlnj

for:

-
  matrix:
    only:
      - image: Visual Studio 2017
      
  build_script:
    - deploy\win32\build-32.bat

-
  matrix:
    only:
      - image: Visual Studio 2019
      
  build_script:
    - deploy\win64\build-64.bat
  
